name: Keep Alive

on:
  schedule:
    - cron: "0 0 1 * *"  # runs on the 1st of every month at 00:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Keeping repository active"
